# This is a basic workflow to help you get started with Actions

name: Changelog check


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request: 
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      changelog:
        description: Which file to use for checking that the changelog was modified
        required: false
        default: changelog.md



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Check-Changelog:
    runs-on: self-hosted
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - name: check for changes
        env:
          BASE_REF: ${{ github.event.pull_request.base.ref }}
          NO_CHANGELOG_LABEL: ${{ contains(github.event.pull_request.labels.*.name, 'no changelog') }}
        run: ${{ github.action_path }}/check.sh "${{ inputs.changelog }}"
        shell: bash

        
